version: "3"
services: 
    app:
        container_name: task-manager
        # restart: always
        # environment: 
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: 4746
        build: .
        ports: 
            - "8000:8000"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"